targets:
  $default:
    builders:
      freezed:
        enabled: true
      json_serializable:
        options:
          field_rename: snake
          checked: true
          explicit_to_json: true
